export const rankingData = [
  { path: "/home", visits: "125.432", percentage: 42, id: 1 },
  {
    path: "/produtos/cdb-banco-master",
    visits: "45.198",
    percentage: 15,
    id: 2,
  },
  { path: "/minha-carteira", visits: "38.541", percentage: 12, id: 3 },
  { path: "/relatorios/mensal", visits: "24.102", percentage: 8, id: 4 },
  { path: "/configuracoes", visits: "18.333", percentage: 6, id: 5 },
  { path: "/perfil/seguranca", visits: "12.400", percentage: 4, id: 6 },
  { path: "/produtos/renda-fixa", visits: "10.050", percentage: 3, id: 7 },
  {
    path: "/produtos/fundos-imobiliarios",
    visits: "8.900",
    percentage: 3,
    id: 8,
  },
  { path: "/suporte/chat", visits: "6.200", percentage: 2, id: 9 },
  { path: "/extrato", visits: "4.500", percentage: 1.5, id: 10 },
  { path: "/produtos/acoes/petr4", visits: "3.200", percentage: 1, id: 11 },
  { path: "/produtos/debentures", visits: "2.800", percentage: 0.9, id: 12 },
  { path: "/suporte/faq", visits: "2.100", percentage: 0.7, id: 13 },
  {
    path: "/produtos/tesouro-direto",
    visits: "1.500",
    percentage: 0.5,
    id: 14,
  },
  { path: "/onboarding/step-1", visits: "800", percentage: 0.2, id: 15 },
  { path: "/termo-de-uso", visits: "400", percentage: 0.1, id: 16 },
  { path: "/politica-privacidade", visits: "300", percentage: 0.1, id: 17 },
  { path: "/produtos/acoes/vale3", visits: "250", percentage: 0.1, id: 18 },
  { path: "/perfil/notificacoes", visits: "150", percentage: 0.05, id: 19 },
  { path: "/esqueci-senha", visits: "120", percentage: 0.04, id: 20 },
];
